@token=yY-QnXPzf9d_7yKm2-kK
GET http://192.168.1.21/api/v4/projects/?with_programming_language=vue HTTP/1.1
PRIVATE-TOKEN: {{token}}

###
GET http://192.168.1.21/findsoft/ppcw/badges/main/pipeline.svg HTTP/1.1
PRIVATE-TOKEN: {{token}}